const choice = (name, label, values, required = false) => ({ name, label, type: 'select', options: values.map(([value, text]) => ({ value, label: text })), required })
const text = (name, label, required = false, type = 'text') => ({ name, label, required, type })
const verification = () => choice('verification', 'توثيق المعلومات', [['unknown','غير معروف'],['reported','معلومات مبلّغة'],['verified','تم التحقق من المستند']])
const provenance = [choice('source', 'مصدر المعلومات', [['patient','المريض'],['contact','جهة اتصال'],['clinician','المعالج'],['document','مستند'],['other','آخر']]), text('source_details','تفاصيل المصدر'), text('source_visit','الزيارة المصدر',false,'visit'), text('recorded_on','تاريخ المعلومات',false,'date'), text('notes','ملاحظات',false,'textarea')]
export const recordKinds = [
  { key:'identifiers', label:'وثائق الهوية', fields:[choice('identifier_type','نوع الهوية',[['national_id','رقم وطني'],['passport','جواز سفر'],['other','آخر']],true),text('value','رقم الوثيقة',true),text('issuer','جهة الإصدار'),{...text('issuing_country','رمز البلد المُصدر (مثل SY)'),maxLength:2},verification()] },
  { key:'contacts', label:'جهات الاتصال', fields:[text('name','الاسم',true),text('relationship','صلة القرابة'),text('phone','الهاتف'),text('email','البريد الإلكتروني',false,'email'),text('is_emergency','اتصال للطوارئ',false,'checkbox'),text('is_primary','الاتصال الأساسي',false,'checkbox'),text('notes','ملاحظات',false,'textarea')] },
  { key:'representatives', label:'الممثلون والأوصياء', fields:[text('name','الاسم',true),text('relationship','العلاقة',true),text('phone','الهاتف'),choice('authority_scope','نطاق الصلاحية',[['contact','التواصل'],['records','الاطلاع على السجل'],['decisions','القرارات'],['records_and_decisions','السجل والقرارات']],true),verification(),text('evidence','مرجع إثبات الصلاحية'),text('valid_from','صالح من',false,'date'),text('valid_until','صالح حتى',false,'date')] },
  { key:'allergies', label:'الحساسيات', clinical:true, fields:[text('substance','المادة',true),text('reaction','التفاعل'),choice('severity','الشدة',[['unknown','غير معروف'],['mild','خفيف'],['moderate','متوسط'],['severe','شديد']]),choice('status','الحالة',[['suspected','مشتبه'],['confirmed','مؤكد'],['refuted','مستبعد'],['resolved','زائل'],['entered_in_error','إدخال خاطئ']]),...provenance] },
  { key:'medications', label:'الأدوية المستمرة', clinical:true, fields:[text('name','الدواء',true),text('dosage','الجرعة'),text('schedule','التعليمات'),choice('status','الحالة',[['active','مستمر'],['on_hold','معلق'],['stopped','متوقف'],['entered_in_error','إدخال خاطئ']]),text('started_on','تاريخ البدء',false,'date'),text('ended_on','تاريخ الانتهاء',false,'date'),...provenance] },
  { key:'follow-ups', label:'إجراءات المتابعة', clinical:true, fields:[text('title','الإجراء المطلوب',true),text('owner','المسؤول',false,'member'),text('due_date','تاريخ الاستحقاق',true,'date'),choice('status','النتيجة',[['pending','قيد المتابعة'],['completed','منجز'],['missed','فائت'],['cancelled','ملغى'],['waived','معفى']]),text('source_visit','الزيارة المصدر',false,'visit'),text('appointment','الموعد المرتبط',false,'appointment'),text('completed_visit','زيارة الإنجاز',false,'visit'),text('notes','ملاحظات',false,'textarea'),text('outcome_reason','سبب النتيجة')] },
]
export const defaultRecord = { identifier_type:'national_id', verification:'reported', severity:'unknown', source:'patient' }
